target 'GrocoLoco' do
use_frameworks!

pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'IQKeyboardManager'
pod 'MMDrawerController', '~> 0.4.0'
pod 'MMDrawerController+Storyboard'






end

